version: '3.8' # La version de la spécification Docker Compose utilisée.

services: 
  nginx: # Service pour le serveur NGINX.
    image: nginx:latest 
    container_name: gateway 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8080:8080"
    networks:
      - app-network 
    depends_on: 
      - auth
      - public
      - private
      - restaurants

  public:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: public-service
    ports:
      - "3001:3000"
    networks:
      - app-network

  restaurants:
    build:
      context: ./restaurants
      dockerfile: Dockerfile
    container_name: restaurants-service
    ports:
      - "3003:3000"
    networks:
      - app-network


  articles:
    build:
      context: ./articles
      dockerfile: Dockerfile
    container_name: articles-service
    ports:
      - "3004:3000"
    networks:
      - app-network

  menus:
    build:
      context: ./menus
      dockerfile: Dockerfile
    container_name: menus-service
    ports:
      - "3005:3000"
    networks:
      - app-network

  commandes:
    build:
      context: ./commandes
      dockerfile: Dockerfile
    container_name: commandes-service
    ports:
      - "3006:3000"
    networks:
      - app-network

  livraisons:
    build:
      context: ./livraisons
      dockerfile: Dockerfile
    container_name: livraisons-service
    ports:
      - "3007:3000"
    networks:
      - app-network
  
  paiements:
    build:
      context: ./paiements
      dockerfile: Dockerfile
    container_name: paiements-service
    ports:
      - "3008:3000"
    networks:
      - app-network

  private:
    build:
      context: ./private
      dockerfile: Dockerfile
    container_name: private-service
    ports:
      - "3002:3000"
    networks:
      - app-network

  db: # Service pour PostgreSQL
    image: postgres:latest
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth: 
    build: 
      context: ./auth # Répertoire contenant le Dockerfile
      dockerfile: Dockerfile 
    container_name: auth-service 
    ports:
      - "3000:3000" 
    networks:
      - app-network 
    environment: 
      - JWT_KEY=API
      - JWT_REFRESH_KEY=NODE
      - PORT=3000 
      - DB_HOST=db
      - DB_NAME=auth_db
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
    depends_on:
      - db

networks:
  app-network:
    driver: bridge 

volumes:
  postgres_data:
