events {
        #déclare les connexions simultanées maximales que chaque processus worker peut gérer.
        #Par défaut, 1024 est une valeur standard pour un usage local ou de faible charge.
    worker_connections 1024;
}

http {
    server {
        #listen 8080 : Correct. Cela configure le serveur pour écouter sur le port 8080.
        #server_name localhost : Correct pour un usage local. Si ce serveur est déployé publiquement,
        #il faudra remplacer localhost par un domaine approprié.
        listen 8080;
        server_name localhost;

        root /usr/share/nginx/html;
        # Public service
        location /public {
            proxy_pass http://public-service:3000/;
        }

        # Restaurants service
        location /restaurants {
            proxy_pass http://restaurants-service:3000/restaurants;
        }

        # Article service
        location /articles {
            proxy_pass http://articles-service:3000/articles;
        }

        # Menu service
        location /menus {
            proxy_pass http://menus-service:3000/menus;
        }

        # Commandes service
        location /commandes {
            proxy_pass http://commandes-service:3000/commandes;
        }

        # Livraisons service
        location /livraisons {
            proxy_pass http://livraisons-service:3000/livraisons;
        }

        # paiements service
        location /paiements {
            proxy_pass http://paiements-service:3000/paiements;
        }

        # Private service
        location /private {
            auth_request /authenticate;
            auth_request_set $auth_status $upstream_status;
            auth_request_set $user_role $upstream_http_x_user_role;
            proxy_set_header X-User-Role $user_role;
            proxy_pass http://private-service:3000/;
        }

        location /authenticate {
            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                return 204;
            }

            proxy_pass http://auth-service:3000/authenticate;
        }

        location /logs {
            if ($request_method = OPTIONS) {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE' always;
                add_header 'Access-Control-Allow-Headers' 'Authorization, Content-Type' always;
                add_header 'Access-Control-Allow-Credentials' 'true' always;
                return 204;
            }

            proxy_pass http://logs-service:3000/logs;
        }
        #Ces directives redirigent les requêtes vers les endpoints correspondants de l'API.

        location /login {
            proxy_pass http://auth-service:3000/login;
        }

        location /register {
            proxy_pass http://auth-service:3000/register;
        }

        location /delete {
            proxy_pass http://auth-service:3000/delete;
        }

        location /update {
            proxy_pass http://auth-service:3000/update;
        }

         location /refreshToken {
            proxy_pass http://auth-service:3000/refreshToken;
        }
    }
}